[project]
name = "live-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "sounddevice",
    "edge-tts",
    "pyside6>=6.5",
    "fastapi>=0.136.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "playwright>=1.60.0",
    "psutil>=7.2.2",
    "pycryptodome>=3.23.0",
    "requests>=2.34.2",
    "uvicorn>=0.47.0",
    "pyinstaller>=6.11.1",
    "pyinstaller-hooks-contrib>=2025.1",
    "faster-whisper>=1.2.1",
    "cos-python-sdk-v5>=1.9.44",
    "python-dotenv>=1.2.2",
]

[tool.setuptools]
packages = ["live_agent"]
